apiVersion: v1
kind: Service
metadata:
  name: zap-svc
spec:
  selector:
    app: zaproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: proxy-port
    - protocol: TCP
      port: 9090 
      targetPort: 9090
      name: shutdown-trigger-port
