apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-deployment
  labels:
    app: zaproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zaproxy
  template:
    metadata:
      labels:
        app: zaproxy
    spec:
      containers:
      - name: zaproxy
        image: zap-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/zap-ready
          initialDelaySeconds: 5
          periodSeconds: 5
