name: Build and Run Integration Tests Docker
on:
  workflow_dispatch:
  schedule:
    # Every day at the 1am
    - cron:  '0 1 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    name: Build, Push and Run Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: docker/Dockerfile-tests
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Run install tests
        run: docker run --rm -t ${{ steps.meta.outputs.tags }}:latest wrk/install_tests.sh
      - 
        name: Run python tests
        run: docker run --rm -t ${{ steps.meta.outputs.tags }}:latest wrk/python_tests.sh
      - 
        name: Run baseline tests
        run: docker run --rm -t ${{ steps.meta.outputs.tags }}:latest wrk/baseline_tests.sh
      - 
        name: Automation Framework context tests
        run: docker run --rm -t ${{ steps.meta.outputs.tags }}:latest wrk/af_context_tests.sh
      - 
        name: Automation Framework plan tests
        run: docker run --rm -t ${{ steps.meta.outputs.tags }}:latest wrk/af_plan_tests.sh